server:
  port: 8081
  contextPath: "!tool"

solon.app:
  name: 'ai-tools'
  group: 'dustin'

solon.logging:
  appender:
    console:
      level: DEBUG
    file:
      level: INFO


# 配置数据源对应的 mybatis 信息（要与 DataSource bean 的名字对上）
mybatis.dynamic:
  typeAliases:    #支持包名 或 类名（大写开头 或 *）//支持 ** 或 * 占位符
    - "com.dustin.ai.**.entity"
  mappers:        #支持包名 或 类名（大写开头 或 *）或 xml（.xml结尾）//支持 ** 或 * 占位符
    - "com.dustin.ai.**.mapper"
    - "classpath:mapper/*.xml"
  configuration:   #扩展配置（要与 MybatisConfiguration 类的属性一一对应）
    cacheEnabled: false
    mapperVerifyEnabled: true #如果为 true，则要求所有 mapper 有 @Mapper 主解
    mapUnderscoreToCamelCase: true
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
  globalConfig:    #全局配置（要与 GlobalConfig 类的属性一一对应）
    banner: false

#
#

# db_user 为动态数据源（主菜是这里!!!）
solon.dataSources:
  dynamic!:
    class: "org.noear.solon.data.dynamicds.DynamicDataSource"
    strict: true #严格模式（指定的源不存时：严格模式会抛异常；非严格模式用默认源）
    default: "db1" #指定默认数据源
    db1:
      ip: 127.0.0.1
      name: ai
      type: "com.zaxxer.hikari.HikariDataSource"
      jdbcUrl: jdbc:mysql://${solon.dataSources.dynamic!.db1.ip}:3306/${solon.dataSources.dynamic!.db1.name}?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: password
    db2:
      ip: 127.0.0.1
      name: ai2
      type: "com.zaxxer.hikari.HikariDataSource"
      jdbcUrl: jdbc:mysql://${solon.dataSources.dynamic!.db2.ip}:3306/${solon.dataSources.dynamic!.db2.name}?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: password

